/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wbc_calculator_JniTest */

#ifndef _Included_com_wbc_calculator_JniTest
#define _Included_com_wbc_calculator_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wbc_calculator_JniTest
 * Method:    add
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_wbc_calculator_JniTest_add
  (JNIEnv *, jclass);

/*
 * Class:     com_wbc_calculator_JniTest
 * Method:    min
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_wbc_calculator_JniTest_min
  (JNIEnv *, jclass);

/*
 * Class:     com_wbc_calculator_JniTest
 * Method:    mul
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_wbc_calculator_JniTest_mul
  (JNIEnv *, jclass);

/*
 * Class:     com_wbc_calculator_JniTest
 * Method:    div
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_wbc_calculator_JniTest_div
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
